### ISSUE TITLE
Använda default rubocop config med overrides istf speca alla regler

### ISSUE THREAD

**Issue by yboulkaid** [bukowskis/style-guide#11]
Idag har vi checkat in i repo:t rubocops master config filen med alla cops och har ändrat lite saker.

Det finns några problem med denna approachen :
- Filen är för stor och ingen kommer att läsa det
- Mest av filen är bara defaults, dvs bara en liten del av filen innehåller "användbar" information.
- Rubocop andrar sina defaults och flyttar cops runt mellan versioner. Vår fil är redan outdated

@mmzoo föreslog att vi istället switchar till en config där vi implicit har alla rubocop defaults och checkar in bara reglerna som vi overridar. Jag tycker att det är en bra idé.

Nackdelen är att vi tappar explicita regler vi använder. Men jag tycker att det fungerar lika bra att ha rubocop regler som våra regler.

**Comment by mmzoo** [comment]
Det går att ytterligare overrida då med specifika grejer så här: https://github.com/bukowskis/ios-app/blob/master/.rubocop.yml

**Comment by mmzoo** [comment]
Vi ska bara inte glöma at hårdspec:a rubocop versionen och uppgradea när vi känner för det. För att defaults kan då ändras i ruby-världen.

**Comment by jens** [comment]
Låter vettigt. Eftersom Code Climate inte verkar kommentera direkt på commits så funderar jag på att börja använda Hound igen.

**Comment by mmzoo** [comment]
Said and done.
