### ISSUE TITLE
Suggestion: Use default `EmptyLinesAroundClassBody`

### ISSUE THREAD

**Issue by mmzoo** [bukowskis/style-guide#33]
Currently we disable [these three cops](https://github.com/bukowskis/style-guide/blob/276fad936bfb863348bf817e9ccab6f5b2cff2a8/rubocop.yml#L103-L104). I think we should use the community standard and propose to remove the disabling.

I really got to appreciate to that cop over time and think it's better than our wild west approach :)

**Comment by yboulkaid** [comment]
No strong opinions about this for me. It'd be nice to adhere to the community standard more so :+1:

**Comment by pidu** [comment]
So the change is to enforce extra empty lines? Not something that seems very useful to me.

**Comment by mmzoo** [comment]
It's the othe way around. We delete the empty lines. That's what default rubocop suggests.

**Comment by mmzoo** [comment]
See https://github.com/bukowskis/style-guide/pull/34
